### ISSUE TITLE
Errors compiling

### ISSUE THREAD

**Issue by fivefortyfour** [h4yn0nnym0u5e/audio-guestbook#1]
`Arduino: 1.8.19 (Windows 10), TD: 1.57, Board: "Teensy 4.0, Serial + MTP Disk (Experimental), 600 MHz, Faster, US English"

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:49:1: error: 'AudioPlaySdWavX' does not name a type

 AudioPlaySdWavX              playWav1; // Play 44.1kHz 16-bit PCM greeting WAV file

 ^

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:54:28: error: 'playWav1' was not declared in this scope

 AudioConnection patchCord3(playWav1, 0, mixer, 1); // wav file playback mixer

                            ^

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino: In function 'void loop()':

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:185:7: error: 'playWav1' was not declared in this scope

       playWav1.play("greeting.wav");    

       ^

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino: In function 'void playAllRecordings()':

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:374:7: error: 'playWav1' was not declared in this scope

       playWav1.play(entry.name());

       ^

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:380:13: error: 'playWav1' was not declared in this scope

     while (!playWav1.isStopped()) { // this works for playWav

             ^

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino: In function 'void playLastRecording()':

C:\Users\conce\Downloads\audio-guestbook-bugfix-better-recording\audio-guestbook-bugfix-better-recording\audio-guestbook\audio-guestbook.ino:411:7: error: 'playWav1' was not declared in this scope

       playWav1.play(filename);

       ^

Error compiling for board Teensy 4.0.

Invalid library found in C:\Program Files (x86)\Arduino\libraries\SDBackup: no headers files (.h) found in C:\Program Files (x86)\Arduino\libraries\SDBackup

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by alexbirtwell** [comment]
@fivefortyfour how did you get past this issue?

**Comment by alexbirtwell** [comment]
ah in fact assuming you moved the "play_sd_wav.h" into the sketch folder?

**Comment by h4yn0nnym0u5e** [comment]
See improved documentation at https://github.com/h4yn0nnym0u5e/audio-guestbook/tree/feature/doc-01 - this should help ensure you get all files in the right place. 

You shouldn't need to move anything into the sketch folder, the downloaded files should all be placed in a correctly named and located sketch folder.

Closing as there's no (code) issue to fix here.
