### ISSUE TITLE
Can't play WAV files

### ISSUE THREAD

**Issue by fivefortyfour** [h4yn0nnym0u5e/audio-guestbook#2]
Some of my wav files play on my laptop, some don't. I have my teensy plugged in to laptop with USB. I can see the teensy folder and the files but it seems like the files are in use, no matter how many messages I record. #

When are the files accessible?

**Comment by h4yn0nnym0u5e** [comment]
Try unplugging and plugging back in, then immediately copying the files off the Teensy to your laptop before trying to play them. This is probably related to MTP stuff, which I can't fully claim to understand.

**Comment by h4yn0nnym0u5e** [comment]
No further response, assuming closed
