### ISSUE TITLE
Memory card full

### ISSUE THREAD

**Issue by fivefortyfour** [h4yn0nnym0u5e/audio-guestbook#3]
I used my phone at an event. For some reason a massive audio file was recorded - assuming it was left off the hook...
Resulting in the memory card being full, so no further recordings were saved.

Has anyone found a way to edit the code so that it limits file size perhaps? I know I can use a bigger memory card but wanted to stop huge files being written

**Comment by h4yn0nnym0u5e** [comment]
When recording starts, store millis() in a variable, say recStartTime
When millis() - recStartTime gets over whatever limit you set, stop recording

Closing as not a code issue, it's a feature suggestion. I'm not adding features, as the original author doesn't seem interested in supporting his project.
